var products=
[
  {
    "productId": "US-0-001",
    "productName": "Papain",
    "productNameCht": "美國木瓜酵素",
    "specification": "34 TU/mg\n(2000 PU/mg)",
    "specificationCht": "34 TU/mg\n(2000 PU/mg)",
    "origin": "美國",
    "patent": "",
    "originExam": "",
    "sgs": "",
    "organic": "",
    "certs": "KOSHER\nHALAL",
    "dosage": "1-2 g/day",
    "targetSymptom": "腸道保健",
    "category": "幫助消化",
    "effects": "幫助消化，分解蛋白質",
    "MOQ": "20-25KG",
    "MOHWRegulation": ""
  },
  {
    "productId": "US-0-002",
    "productName": "Fungal Protease",
    "productNameCht": "美國蛋白酵素",
    "specification": "5000 HUT/g",
    "specificationCht": "5000 HUT/g",
    "origin": "美國",
    "patent": "",
    "originExam": "",
    "sgs": "",
    "organic": "",
    "certs": "KOSHER\nHALAL",
    "dosage": "6-12 g/day",
    "targetSymptom": "腸道保健",
    "category": "幫助消化",
    "effects": "幫助消化，分解蛋白質",
    "MOQ": "20-25KG",
    "MOHWRegulation": ""
  },
  {
    "productId": "US-0-003",
    "productName": "Lipase",
    "productNameCht": "美國解脂酵素",
    "specification": "1500 FIP/g",
    "specificationCht": "1500 FIP/g",
    "origin": "美國",
    "patent": "",
    "originExam": "",
    "sgs": "",
    "organic": "",
    "certs": "KOSHER\nHALAL",
    "dosage": "1-4 g/day",
    "targetSymptom": "腸道保健",
    "category": "幫助消化",
    "effects": "幫助消化，分解脂肪",
    "MOQ": "20-25KG",
    "MOHWRegulation": ""
  },
  {
    "productId": "US-0-004",
    "productName": "Fungal Amylase",
    "productNameCht": "美國澱粉酵素",
    "specification": "25000 SKB/g",
    "specificationCht": "25000 SKB/g",
    "origin": "美國",
    "patent": "",
    "originExam": "",
    "sgs": "",
    "organic": "",
    "certs": "KOSHER\nHALAL",
    "dosage": "600 mg/day",
    "targetSymptom": "腸道保健",
    "category": "幫助消化",
    "effects": "幫助消化，分解澱粉",
    "MOQ": "20-25KG",
    "MOHWRegulation": ""
  },
  {
    "productId": "US-0-005",
    "productName": "Lactase",
    "productNameCht": "美國乳糖酵素",
    "specification": "1000 ALU/g",
    "specificationCht": "1000 ALU/g",
    "origin": "美國",
    "patent": "",
    "originExam": "",
    "sgs": "",
    "organic": "",
    "certs": "KOSHER\nHALAL",
    "dosage": "9-10 g/day",
    "targetSymptom": "腸道保健",
    "category": "幫助消化",
    "effects": "幫助消化，分解乳糖",
    "MOQ": "20-25KG",
    "MOHWRegulation": ""
  },
  {
    "productId": "IN-0-001",
    "productName": "Bromelain(Odourless)",
    "productNameCht": "印度鳳梨酵素",
    "specification": "2400 GDU/g",
    "specificationCht": "2400 GDU/g",
    "origin": "印度",
    "patent": "",
    "originExam": "",
    "sgs": "",
    "organic": "",
    "certs": "HALAL",
    "dosage": "0.5 g/day",
    "targetSymptom": "腸道保健\n關節保健",
    "category": "幫助消化",
    "effects": "幫助消化，分解蛋白質\n抗發炎",
    "MOQ": "1KG",
    "MOHWRegulation": ""
  },
  {
    "productId": "IN-0-002",
    "productName": "Bromelain(Odourless)",
    "productNameCht": "印度鳳梨酵素",
    "specification": "1200 GDU/g",
    "specificationCht": "1200 GDU/g",
    "origin": "印度",
    "patent": "",
    "originExam": "",
    "sgs": "",
    "organic": "",
    "certs": "HALAL",
    "dosage": "1 g/day",
    "targetSymptom": "腸道保健\n關節保健",
    "category": "幫助消化",
    "effects": "幫助消化，分解蛋白質\n抗發炎",
    "MOQ": "1KG",
    "MOHWRegulation": ""
  },
  {
    "productId": "IN-003",
    "productName": "Psyllium seed husk powder",
    "productNameCht": "洋車前子殼粉",
    "specification": "98%、80目",
    "specificationCht": "98%、80目",
    "origin": "印度",
    "patent": "",
    "originExam": "",
    "sgs": "生菌數\n重金屬\n310項農藥",
    "organic": "美國USDA\n歐盟ECOCERT",
    "certs": "KOSHER\nHALAL",
    "dosage": "5-10 g/day",
    "targetSymptom": "體重管理\n血糖管理",
    "category": "排便順暢",
    "effects": "飽足感\n延緩血糖上升",
    "MOQ": "25KG",
    "MOHWRegulation": "劑量、警語"
  },
  {
    "productId": "IN-004",
    "productName": "Psyllium seed husk",
    "productNameCht": "洋車前子殼",
    "specification": "99%",
    "specificationCht": "99%",
    "origin": "印度",
    "patent": "",
    "originExam": "",
    "sgs": "",
    "organic": "美國USDA\n歐盟ECOCERT",
    "certs": "KOSHER\nHALAL",
    "dosage": "5-10 g/day",
    "targetSymptom": "體重管理\n血糖管理",
    "category": "排便順暢",
    "effects": "飽足感\n延緩血糖上升",
    "MOQ": "25KG",
    "MOHWRegulation": "劑量、警語"
  },
  {
    "productId": "TW-001",
    "productName": "Napiergrass powder",
    "productNameCht": "牧草粉(台畜二號)",
    "specification": "",
    "specificationCht": "",
    "origin": "台灣",
    "patent": "",
    "originExam": "",
    "sgs": "310項農藥\n生菌數重金屬",
    "organic": "",
    "certs": "-",
    "dosage": "適量",
    "targetSymptom": "體重管理",
    "category": "排便順暢",
    "effects": "飽足感",
    "MOQ": "25KG",
    "MOHWRegulation": ""
  },
  {
    "productId": "TW-002",
    "productName": "Napiergrass powder",
    "productNameCht": "牧草粉(台畜五號)",
    "specification": "Anthocyanin 50 mg/100g\nDietary fiber 60g/100g",
    "specificationCht": "花青素 50 mg/100g\n膳食纖維 60g/100g",
    "origin": "台灣",
    "patent": "",
    "originExam": "",
    "sgs": "總花青素\n膳食纖維",
    "organic": "",
    "certs": "-",
    "dosage": "適量",
    "targetSymptom": "體重管理",
    "category": "排便順暢",
    "effects": "飽足感",
    "MOQ": "25KG",
    "MOHWRegulation": ""
  }
]